// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "xml2_types.h"
#include <Rcpp.h>

using namespace Rcpp;

// parse_xml_file
XPtr<XmlDocPtr> parse_xml_file(std::string path, std::string encoding = "", int options = 0);
RcppExport SEXP xml2_parse_xml_file(SEXP pathSEXP, SEXP encodingSEXP, SEXP optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type encoding(encodingSEXP);
    Rcpp::traits::input_parameter< int >::type options(optionsSEXP);
    __result = Rcpp::wrap(parse_xml_file(path, encoding, options));
    return __result;
END_RCPP
}
// parse_xml_string
XPtr<XmlDocPtr> parse_xml_string(CharacterVector x, std::string encoding, std::string base_url = "", int options = 0);
RcppExport SEXP xml2_parse_xml_string(SEXP xSEXP, SEXP encodingSEXP, SEXP base_urlSEXP, SEXP optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type encoding(encodingSEXP);
    Rcpp::traits::input_parameter< std::string >::type base_url(base_urlSEXP);
    Rcpp::traits::input_parameter< int >::type options(optionsSEXP);
    __result = Rcpp::wrap(parse_xml_string(x, encoding, base_url, options));
    return __result;
END_RCPP
}
// xml_doc_format
CharacterVector xml_doc_format(XPtr<XmlDocPtr> x);
RcppExport SEXP xml2_xml_doc_format(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< XPtr<XmlDocPtr> >::type x(xSEXP);
    __result = Rcpp::wrap(xml_doc_format(x));
    return __result;
END_RCPP
}
// xml_doc_root
XPtr<XmlNode> xml_doc_root(XPtr<XmlDocPtr> x);
RcppExport SEXP xml2_xml_doc_root(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< XPtr<XmlDocPtr> >::type x(xSEXP);
    __result = Rcpp::wrap(xml_doc_root(x));
    return __result;
END_RCPP
}
// xml_name
CharacterVector xml_name(XPtr<XmlNode> node);
RcppExport SEXP xml2_xml_name(SEXP nodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< XPtr<XmlNode> >::type node(nodeSEXP);
    __result = Rcpp::wrap(xml_name(node));
    return __result;
END_RCPP
}
// new_push_parser
XPtr<XmlPushParserPtr> new_push_parser(std::string filename);
RcppExport SEXP xml2_new_push_parser(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    __result = Rcpp::wrap(new_push_parser(filename));
    return __result;
END_RCPP
}
// feed_push_parser_text
bool feed_push_parser_text(XPtr<XmlPushParserPtr> x, const char* text, int size);
RcppExport SEXP xml2_feed_push_parser_text(SEXP xSEXP, SEXP textSEXP, SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< XPtr<XmlPushParserPtr> >::type x(xSEXP);
    Rcpp::traits::input_parameter< const char* >::type text(textSEXP);
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    __result = Rcpp::wrap(feed_push_parser_text(x, text, size));
    return __result;
END_RCPP
}
// feed_push_parser_raw
bool feed_push_parser_raw(XPtr<XmlPushParserPtr> x, SEXP data);
RcppExport SEXP xml2_feed_push_parser_raw(SEXP xSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< XPtr<XmlPushParserPtr> >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    __result = Rcpp::wrap(feed_push_parser_raw(x, data));
    return __result;
END_RCPP
}
// close_push_parser
bool close_push_parser(XPtr<XmlPushParserPtr> x);
RcppExport SEXP xml2_close_push_parser(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< XPtr<XmlPushParserPtr> >::type x(xSEXP);
    __result = Rcpp::wrap(close_push_parser(x));
    return __result;
END_RCPP
}
// get_push_parser_doc
XPtr<XmlDocPtr> get_push_parser_doc(XPtr<XmlPushParserPtr> x);
RcppExport SEXP xml2_get_push_parser_doc(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< XPtr<XmlPushParserPtr> >::type x(xSEXP);
    __result = Rcpp::wrap(get_push_parser_doc(x));
    return __result;
END_RCPP
}
