# Generated by cpp11: do not edit by hand

read_connection_ <- function(con_sxp, read_size_sxp) {
  .Call(`_xml2_read_connection_`, con_sxp, read_size_sxp)
}

xml_parse_options_ <- function() {
  .Call(`_xml2_xml_parse_options_`)
}

doc_parse_file <- function(path_sxp, encoding_sxp, as_html_sxp, options_sxp) {
  .Call(`_xml2_doc_parse_file`, path_sxp, encoding_sxp, as_html_sxp, options_sxp)
}

doc_parse_raw <- function(x, encoding_sxp, base_url_sxp, as_html_sxp, options_sxp) {
  .Call(`_xml2_doc_parse_raw`, x, encoding_sxp, base_url_sxp, as_html_sxp, options_sxp)
}

doc_root <- function(x) {
  .Call(`_xml2_doc_root`, x)
}

doc_has_root <- function(x_sxp) {
  .Call(`_xml2_doc_has_root`, x_sxp)
}

doc_url <- function(doc_sxp) {
  .Call(`_xml2_doc_url`, doc_sxp)
}

doc_new <- function(version_sxp, encoding_sxp) {
  .Call(`_xml2_doc_new`, version_sxp, encoding_sxp)
}

doc_set_root <- function(doc_sxp, root_sxp) {
  .Call(`_xml2_doc_set_root`, doc_sxp, root_sxp)
}

doc_is_html <- function(doc_sxp) {
  .Call(`_xml2_doc_is_html`, doc_sxp)
}

init_libxml2 <- function() {
  .Call(`_xml2_init_libxml2`)
}

libxml2_version_ <- function() {
  .Call(`_xml2_libxml2_version_`)
}

unique_ns <- function(ns) {
  .Call(`_xml2_unique_ns`, ns)
}

doc_namespaces <- function(doc_sxp) {
  .Call(`_xml2_doc_namespaces`, doc_sxp)
}

ns_lookup_uri <- function(doc_sxp, node_sxp, uri_sxp) {
  .Call(`_xml2_ns_lookup_uri`, doc_sxp, node_sxp, uri_sxp)
}

ns_lookup <- function(doc_sxp, node_sxp, prefix_sxp) {
  .Call(`_xml2_ns_lookup`, doc_sxp, node_sxp, prefix_sxp)
}

node_name <- function(node_sxp, nsMap) {
  .Call(`_xml2_node_name`, node_sxp, nsMap)
}

node_set_name <- function(node_sxp, value) {
  .Call(`_xml2_node_set_name`, node_sxp, value)
}

node_text <- function(node_sxp) {
  .Call(`_xml2_node_text`, node_sxp)
}

node_attr <- function(node_sxp, name_sxp, missing_sxp, nsMap_sxp) {
  .Call(`_xml2_node_attr`, node_sxp, name_sxp, missing_sxp, nsMap_sxp)
}

node_attrs <- function(node_sxp, nsMap_sxp) {
  .Call(`_xml2_node_attrs`, node_sxp, nsMap_sxp)
}

node_set_attr <- function(node_sxp, name_sxp, value, nsMap) {
  .Call(`_xml2_node_set_attr`, node_sxp, name_sxp, value, nsMap)
}

node_remove_attr <- function(node_sxp, name_sxp, nsMap) {
  .Call(`_xml2_node_remove_attr`, node_sxp, name_sxp, nsMap)
}

node_children <- function(node_sxp, only_node_sxp) {
  .Call(`_xml2_node_children`, node_sxp, only_node_sxp)
}

node_length <- function(node_sxp, only_node_sxp) {
  .Call(`_xml2_node_length`, node_sxp, only_node_sxp)
}

node_has_children <- function(node_sxp, only_node_sxp) {
  .Call(`_xml2_node_has_children`, node_sxp, only_node_sxp)
}

node_parents <- function(node_sxp) {
  .Call(`_xml2_node_parents`, node_sxp)
}

node_siblings <- function(node_sxp, only_node_sxp) {
  .Call(`_xml2_node_siblings`, node_sxp, only_node_sxp)
}

node_parent <- function(node_sxp) {
  .Call(`_xml2_node_parent`, node_sxp)
}

node_path <- function(node_sxp) {
  .Call(`_xml2_node_path`, node_sxp)
}

nodes_duplicated <- function(nodes) {
  .Call(`_xml2_nodes_duplicated`, nodes)
}

node_type <- function(node_sxp) {
  .Call(`_xml2_node_type`, node_sxp)
}

node_copy <- function(node_sxp) {
  .Call(`_xml2_node_copy`, node_sxp)
}

node_set_content <- function(node_sxp, content) {
  .Call(`_xml2_node_set_content`, node_sxp, content)
}

node_append_content <- function(node_sxp, content) {
  .Call(`_xml2_node_append_content`, node_sxp, content)
}

node_new_text <- function(node_sxp, content) {
  .Call(`_xml2_node_new_text`, node_sxp, content)
}

node_append_child <- function(parent_sxp, cur_sxp) {
  .Call(`_xml2_node_append_child`, parent_sxp, cur_sxp)
}

node_prepend_child <- function(parent_sxp, cur_sxp) {
  .Call(`_xml2_node_prepend_child`, parent_sxp, cur_sxp)
}

node_prepend_sibling <- function(cur_sxp, elem_sxp) {
  .Call(`_xml2_node_prepend_sibling`, cur_sxp, elem_sxp)
}

node_append_sibling <- function(cur_sxp, elem_sxp) {
  .Call(`_xml2_node_append_sibling`, cur_sxp, elem_sxp)
}

node_replace <- function(old_sxp, cur_sxp) {
  .Call(`_xml2_node_replace`, old_sxp, cur_sxp)
}

node_remove <- function(node_sxp, free_sxp) {
  .Call(`_xml2_node_remove`, node_sxp, free_sxp)
}

node_new <- function(name) {
  .Call(`_xml2_node_new`, name)
}

node_cdata_new <- function(doc_sxp, content_sxp) {
  .Call(`_xml2_node_cdata_new`, doc_sxp, content_sxp)
}

node_comment_new <- function(content) {
  .Call(`_xml2_node_comment_new`, content)
}

node_new_ns <- function(name, ns_sxp) {
  .Call(`_xml2_node_new_ns`, name, ns_sxp)
}

node_set_namespace_uri <- function(doc_sxp, node_sxp, uri) {
  .Call(`_xml2_node_set_namespace_uri`, doc_sxp, node_sxp, uri)
}

node_set_namespace_prefix <- function(doc_sxp, node_sxp, prefix_sxp) {
  .Call(`_xml2_node_set_namespace_prefix`, doc_sxp, node_sxp, prefix_sxp)
}

node_new_dtd <- function(doc_sxp, name_sxp, eid_sxp, sid_sxp) {
  .Call(`_xml2_node_new_dtd`, doc_sxp, name_sxp, eid_sxp, sid_sxp)
}

xml_save_options_ <- function() {
  .Call(`_xml2_xml_save_options_`)
}

doc_write_file <- function(doc_sxp, path_sxp, encoding_sxp, options_sxp) {
  .Call(`_xml2_doc_write_file`, doc_sxp, path_sxp, encoding_sxp, options_sxp)
}

doc_write_connection <- function(doc_sxp, connection, encoding_sxp, options_sxp) {
  .Call(`_xml2_doc_write_connection`, doc_sxp, connection, encoding_sxp, options_sxp)
}

doc_write_character <- function(doc_sxp, encoding_sxp, options_sxp) {
  .Call(`_xml2_doc_write_character`, doc_sxp, encoding_sxp, options_sxp)
}

node_write_file <- function(node_sxp, path_sxp, encoding_sxp, options_sxp) {
  .Call(`_xml2_node_write_file`, node_sxp, path_sxp, encoding_sxp, options_sxp)
}

node_write_connection <- function(node_sxp, connection, encoding_sxp, options_sxp) {
  .Call(`_xml2_node_write_connection`, node_sxp, connection, encoding_sxp, options_sxp)
}

node_write_character <- function(node_sxp, encoding_sxp, options_sxp) {
  .Call(`_xml2_node_write_character`, node_sxp, encoding_sxp, options_sxp)
}

doc_validate <- function(doc_sxp, schema_sxp) {
  .Call(`_xml2_doc_validate`, doc_sxp, schema_sxp)
}

url_absolute_ <- function(x_sxp, base_sxp) {
  .Call(`_xml2_url_absolute_`, x_sxp, base_sxp)
}

url_relative_ <- function(x_sxp, base_sxp) {
  .Call(`_xml2_url_relative_`, x_sxp, base_sxp)
}

url_parse_ <- function(x_sxp) {
  .Call(`_xml2_url_parse_`, x_sxp)
}

url_escape_ <- function(x_sxp, reserved_sxp) {
  .Call(`_xml2_url_escape_`, x_sxp, reserved_sxp)
}

url_unescape_ <- function(x_sxp) {
  .Call(`_xml2_url_unescape_`, x_sxp)
}

xpath_search <- function(node_sxp, doc_sxp, xpath_sxp, nsMap_sxp, num_results_sxp) {
  .Call(`_xml2_xpath_search`, node_sxp, doc_sxp, xpath_sxp, nsMap_sxp, num_results_sxp)
}
