# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parse_xml_file <- function(path, encoding = "", options = 0L) {
    .Call('xml2_parse_xml_file', PACKAGE = 'xml2', path, encoding, options)
}

parse_xml_string <- function(x, encoding, base_url = "", options = 0L) {
    .Call('xml2_parse_xml_string', PACKAGE = 'xml2', x, encoding, base_url, options)
}

xml_doc_format <- function(x) {
    .Call('xml2_xml_doc_format', PACKAGE = 'xml2', x)
}

xml_doc_root <- function(x) {
    .Call('xml2_xml_doc_root', PACKAGE = 'xml2', x)
}

xml_name <- function(node) {
    .Call('xml2_xml_name', PACKAGE = 'xml2', node)
}

