# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parse_xml_file <- function(path, encoding = "", options = 0L) {
    .Call('xml2_parse_xml_file', PACKAGE = 'xml2', path, encoding, options)
}

parse_xml_string <- function(x, encoding, base_url = "", options = 0L) {
    .Call('xml2_parse_xml_string', PACKAGE = 'xml2', x, encoding, base_url, options)
}

xml_doc_format <- function(x) {
    .Call('xml2_xml_doc_format', PACKAGE = 'xml2', x)
}

xml_doc_root <- function(x) {
    .Call('xml2_xml_doc_root', PACKAGE = 'xml2', x)
}

xml_name <- function(node) {
    .Call('xml2_xml_name', PACKAGE = 'xml2', node)
}

new_push_parser <- function(filename) {
    .Call('xml2_new_push_parser', PACKAGE = 'xml2', filename)
}

feed_push_parser_text <- function(x, text, size) {
    .Call('xml2_feed_push_parser_text', PACKAGE = 'xml2', x, text, size)
}

feed_push_parser_raw <- function(x, data) {
    .Call('xml2_feed_push_parser_raw', PACKAGE = 'xml2', x, data)
}

close_push_parser <- function(x) {
    .Call('xml2_close_push_parser', PACKAGE = 'xml2', x)
}

get_push_parser_doc <- function(x) {
    .Call('xml2_get_push_parser_doc', PACKAGE = 'xml2', x)
}

